// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXsJvId68pej_EBgwpLg8jRLV5dTgAJwk',
    appId: '1:824724579404:web:d67b84111072141d9980e9',
    messagingSenderId: '824724579404',
    projectId: 'my-awesome-03',
    authDomain: 'my-awesome-03.firebaseapp.com',
    storageBucket: 'my-awesome-03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyx1SzL5YBmGCPHYLIqVPg6attdwkYfE4',
    appId: '1:824724579404:android:fa8ac4919c08a5939980e9',
    messagingSenderId: '824724579404',
    projectId: 'my-awesome-03',
    storageBucket: 'my-awesome-03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_M3EeYGomRn-tmH4I2DAJ38vQ4JCxWFI',
    appId: '1:824724579404:ios:a5ff1c74754738b69980e9',
    messagingSenderId: '824724579404',
    projectId: 'my-awesome-03',
    storageBucket: 'my-awesome-03.firebasestorage.app',
    iosBundleId: 'com.example.setuNgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_M3EeYGomRn-tmH4I2DAJ38vQ4JCxWFI',
    appId: '1:824724579404:ios:a5ff1c74754738b69980e9',
    messagingSenderId: '824724579404',
    projectId: 'my-awesome-03',
    storageBucket: 'my-awesome-03.firebasestorage.app',
    iosBundleId: 'com.example.setuNgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXsJvId68pej_EBgwpLg8jRLV5dTgAJwk',
    appId: '1:824724579404:web:d2ac6d89c4e3cb3d9980e9',
    messagingSenderId: '824724579404',
    projectId: 'my-awesome-03',
    authDomain: 'my-awesome-03.firebaseapp.com',
    storageBucket: 'my-awesome-03.firebasestorage.app',
  );

}