// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsgC59wHzAZy-mKgekXDODnHAJ_4tImQU',
    appId: '1:121707566477:web:5c203ffd44a67f4e7299c4',
    messagingSenderId: '121707566477',
    projectId: 'setuu-9ce39',
    authDomain: 'setuu-9ce39.firebaseapp.com',
    storageBucket: 'setuu-9ce39.firebasestorage.app',
    measurementId: 'G-904NJ4M8GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM3WiKKdRQelp-bm-igdQrI_rO7sGq-EM',
    appId: '1:121707566477:android:defb201a40a58d5b7299c4',
    messagingSenderId: '121707566477',
    projectId: 'setuu-9ce39',
    storageBucket: 'setuu-9ce39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByDetslqOumsAfQkrbWAyN3eO6HEFUNdI',
    appId: '1:121707566477:ios:7d7b953feb2fdec87299c4',
    messagingSenderId: '121707566477',
    projectId: 'setuu-9ce39',
    storageBucket: 'setuu-9ce39.firebasestorage.app',
    iosBundleId: 'com.example.setuNgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByDetslqOumsAfQkrbWAyN3eO6HEFUNdI',
    appId: '1:121707566477:ios:7d7b953feb2fdec87299c4',
    messagingSenderId: '121707566477',
    projectId: 'setuu-9ce39',
    storageBucket: 'setuu-9ce39.firebasestorage.app',
    iosBundleId: 'com.example.setuNgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsgC59wHzAZy-mKgekXDODnHAJ_4tImQU',
    appId: '1:121707566477:web:348e12ee601bf4d27299c4',
    messagingSenderId: '121707566477',
    projectId: 'setuu-9ce39',
    authDomain: 'setuu-9ce39.firebaseapp.com',
    storageBucket: 'setuu-9ce39.firebasestorage.app',
    measurementId: 'G-X1CFT8N6DZ',
  );
}
